### PR TITLE
.

### PR DESCRIPTION
**Pull request by weathon**

### CODE REVIEW

**Comment by weathon** [comment]
As soon as this branch has been accepted, I want this be delete -- I don't want CCP knows my github account

**Comment by hongkonggong** [comment]
Hi Wayne – that's not how Github works. if the pull request/branch is
accepted then it's credited and linked to you. please consider deleting it
altogether if you are concerned.

**Comment by weathon** [comment]
How can I delete a PR

**Comment by weathon** [comment]
Maybe you can copy the file and commit it to the repo using your account and then delete this. THANKS

**Comment by MatthewTheGlutton** [comment]
Normally I'd just click on "Close Pull Request" next to the "Comment" button, then delete my fork as applicable.

If you want to delete everything and leave no trace, I don't know if that's possible.

**Comment by weathon** [comment]
Maybe it will be fine

**Pull request closed without merging**
